// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskAssignementManager.Data;

namespace TaskAssignementManager.Data.Migrations
{
    [DbContext(typeof(TasksDbContext))]
    [Migration("20200608163120_AddingSeededData")]
    partial class AddingSeededData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskAssignementManager.Domain.Tasks.TaskGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaskGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4cd3c703-4164-4183-a09d-38eccab3ccad"),
                            Name = "SeedTaskGroup"
                        });
                });

            modelBuilder.Entity("TaskAssignementManager.Domain.Tasks.UserTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("UserTasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("61f3ebd6-b3b8-4012-80c7-29d3cda34fa1"),
                            Deadline = new DateTime(2020, 6, 18, 18, 31, 19, 396, DateTimeKind.Local).AddTicks(2174),
                            GroupId = new Guid("4cd3c703-4164-4183-a09d-38eccab3ccad"),
                            Name = "SeedTask1_Unassigned",
                            Status = 0,
                            UsersId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("f68d2f1a-95c5-432d-ae36-b260c8ca6750"),
                            Deadline = new DateTime(2020, 6, 13, 18, 31, 19, 400, DateTimeKind.Local).AddTicks(9729),
                            GroupId = new Guid("4cd3c703-4164-4183-a09d-38eccab3ccad"),
                            Name = "SeedTask2_Unassigned",
                            Status = 1,
                            UsersId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("6ea08c5e-6a45-4cc0-aa7c-ff93552d140e"),
                            Deadline = new DateTime(2020, 6, 16, 18, 31, 19, 400, DateTimeKind.Local).AddTicks(9864),
                            GroupId = new Guid("4cd3c703-4164-4183-a09d-38eccab3ccad"),
                            Name = "Completed_SeedTask3_AssignedToUnexistingUser",
                            Status = 2,
                            UsersId = new Guid("4a826ac4-fd61-4464-b6c3-246395923e2e")
                        });
                });

            modelBuilder.Entity("TaskAssignementManager.Domain.Tasks.UserTask", b =>
                {
                    b.HasOne("TaskAssignementManager.Domain.Tasks.TaskGroup", "Group")
                        .WithMany("UserTasks")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
